### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eerie** [BleuCadet/deviantart-dl#1]
Traceback (most recent call last):
  File "deviantart-dl.py", line 366, in <module>
    main()
  File "deviantart-dl.py", line 354, in main
    all_pages = count_pages(gallery, source)
  File "deviantart-dl.py", line 179, in count_pages
    found = re.findall('(\d+)</a></li><li class="next"', text)[0]
IndexError: list index out of range

**Comment by klassiker** [comment]
The error occurs when you are trying to download a gallery with less than 3 pages I think. Just add try and except at the sections where the traceback sends you, it will work. You will still get your images. I think I will fix it sometimes if @BleuCadet doesn't responds in time.
Kind Regards
